version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: short-webserver
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  php-fpm:
    build:
      context: ./php
    container_name: short-php-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    stdin_open: true # docker run -i
    tty: true # docker run -t
    expose:
      - '9000'



  mysql:
    image: mysql:8.0
    container_name: short-mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: your_laravel_user_password
    expose:
      - "3306"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: short-redis
    expose:
      - "6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
